fitness_rails/config/routes.rb
Rails.application.routes.draw do
  resources :students
  root "students#index"
end

fitness_rails/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

fitness_rails/app/models/student.rb
class Student < ApplicationRecord

  before_create :before_create

  def before_create
    aluno = SaudeRuby::Aluno.new(peso: self.weitgh, altura: self.height)
    self.imc_number = aluno.imc
    self.imc_classification = SaudeRuby::IMC.classificacao(self.imc_number)
  end
end

fitness_rails/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

fitness_rails/app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: %i[ show edit update destroy ]

  # GET /students or /students.json
  def index
    @students = Student.all
  end

  # GET /students/1 or /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students or /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: "Student was successfully created." }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1 or /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: "Student was successfully updated." }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1 or /students/1.json
  def destroy
    @student.destroy

    respond_to do |format|
      format.html { redirect_to students_path, status: :see_other, notice: "Student was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def student_params
      params.require(:student).permit(:name, :weitgh, :height, :imc_number, :imc_classification)
    end
end

fitness_rails/app/helpers/application_helper.rb
module ApplicationHelper
end

fitness_rails/app/helpers/students_helper.rb
module StudentsHelper
end

fitness_rails/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FitnessRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

fitness_rails/app/views/students/_form.html.erb
<%= form_with(model: student) do |form| %>
  <% if student.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
        <% student.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :weitgh, style: "display: block" %>
    <%= form.text_field :weitgh %>
  </div>

  <div>
    <%= form.label :height, style: "display: block" %>
    <%= form.text_field :height %>
  </div>

  <div>
    <%= form.label :imc_number, style: "display: block" %>
    <%= form.text_field :imc_number %>
  </div>

  <div>
    <%= form.label :imc_classification, style: "display: block" %>
    <%= form.text_field :imc_classification %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

fitness_rails/app/views/students/_student.html.erb
<div id="<%= dom_id student %>">
  <p>
    <strong>Name:</strong>
    <%= student.name %>
  </p>

  <p>
    <strong>Weitgh:</strong>
    <%= student.weitgh %>
  </p>

  <p>
    <strong>Height:</strong>
    <%= student.height %>
  </p>

  <p>
    <strong>Imc number:</strong>
    <%= student.imc_number %>
  </p>

  <p>
    <strong>Imc classification:</strong>
    <%= student.imc_classification %>
  </p>

</div>

fitness_rails/app/views/students/edit.html.erb
<h1>Editing student</h1>

<%= render "form", student: @student %>

<br>

<div>
  <%= link_to "Show this student", @student %> |
  <%= link_to "Back to students", students_path %>
</div>

fitness_rails/app/views/students/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Students</h1>

<div id="students">
  <% @students.each do |student| %>
    <%= render student %>
    <p>
      <%= link_to "Show this student", student %>
    </p>
  <% end %>
</div>

<%= link_to "New student", new_student_path %>

fitness_rails/app/views/students/new.html.erb
<h1>New student</h1>

<%= render "form", student: @student %>

<br>

<div>
  <%= link_to "Back to students", students_path %>
</div>

fitness_rails/app/views/students/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @student %>

<div>
  <%= link_to "Edit this student", edit_student_path(@student) %> |
  <%= link_to "Back to students", students_path %>

  <%= button_to "Destroy this student", @student, method: :delete %>
</div>